# Generated by Django 3.2.13 on 2023-03-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=50)),
                ('em', models.EmailField(max_length=254)),
                ('ps', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userfooditem',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userfooditem',
            name='fooditem',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Fooditem',
        ),
        migrations.DeleteModel(
            name='UserFooditem',
        ),
    ]
