# Generated by Django 3.2.13 on 2023-03-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0004_category_customer_fooditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='carbohydrate',
            new_name='calo',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='fats',
            new_name='carbo',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='protein',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='fooditem',
            old_name='name',
            new_name='fitm',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='prot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
